### ISSUE TITLE
Null pointer in input arguments

### ISSUE THREAD

**Issue by jojo96** [IntelPython/daal4py#308] opened 2020-09-30 06:10 UTC
I am trying the run the notebook @ https://github.com/IntelPython/daal4py/blob/master/examples/daal4py_data_science.ipynb

When I try to run the following block, I get a run time error.
**d4p_lm = d4p.linear_regression_training(interceptFlag=True)
lm_trained = d4p_lm.compute(reduced_dataset.values, target)**

**RuntimeError                              Traceback (most recent call last)
<ipython-input-10-0f7e0d7472b8> in <module>
      1 d4p_lm = d4p.linear_regression_training(interceptFlag=True)
----> 2 lm_trained = d4p_lm.compute(reduced_dataset.values, target)

build\daal4py_cy.pyx in _daal4py.linear_regression_training.compute()

build\daal4py_cy.pyx in _daal4py.linear_regression_training._compute()

RuntimeError: Null pointer in input arguments**

**Comment by KalyanovD** [comment] 2020-10-08 18:38
Hello @jojo96,

Looks like in your case input data wasn't set. This may be caused by some issues with environment or execution process. Could you please provide more information about environment on your machine(versions of dependencies and jupyter and how it was installed)? Does the In[5] and In[7] cells shows correct shapes as in original notebook?

I've tried to reproduce your problem with using conda environment with installed Jupyter Notebook and other dependencies but this notebook finished without errors.

**Comment by PetrovKP** [comment] 2020-12-22 20:11
@jojo96 can we close this issue?

**Closed** 2021-01-27 10:56 UTC
